/** Qwik DOM attribute names used for detection and tree building. */
export const QWIK_ATTR = {
  CONTAINER: 'q:container',
  VERSION: 'q:version',
  RENDER: 'q:render',
  BASE: 'q:base',
  ROUTE: 'q:route',
  MANIFEST_HASH: 'q:manifest-hash',
  /** v1 element identifier */
  ID: 'q:id',
  /** v1 element key */
  KEY: 'q:key',
  /** v2 runtime marker (value `"2"`) */
  RUNTIME: 'q:runtime',
} as const;

export const QWIK_CONTAINER_SELECTOR = '[q\\:container]';

/** v1 virtual node comment tag */
export const VIRTUAL_NODE_TAG = '<!--qv-->';

/** Event attribute prefixes used in v1 */
export const V1_EVENT_PREFIX = {
  COLON: 'on:',
  DASH: 'on-',
} as const;

/** Event attribute prefix used in v2 */
export const V2_EVENT_PREFIX = 'q-e:';

/**
 * v2 uses `:=` as the element binding attribute instead of `q:id`.
 * The colon-equals attribute carries the component binding identifier.
 */
export const V2_BINDING_ATTR = ':';

/** v1 serialization script type */
export const QWIK_JSON_SCRIPT_TYPE = 'qwik/json';

/** v2 serialization script types */
export const QWIK_STATE_SCRIPT_TYPE = 'qwik/state';
export const QWIK_VNODE_SCRIPT_TYPE = 'qwik/vnode';

export const HIGHLIGHT_OVERLAY_ID = '__qwik_dt_highlight';

/** Polling interval (ms) for live DOM state watching */
export const LIVE_POLL_INTERVAL_MS = 800;

/** Timeout (ms) before giving up on initial Qwik detection */
export const DETECTION_TIMEOUT_MS = 3000;

/** Retry delays (ms) for Qwik detection backoff. Tried in order before final timeout. */
export const DETECTION_RETRY_DELAYS = [500, 1000, 2000] as const;

/**
 * Build a safe CSS attribute selector for `q:id` (v1) or `:` (v2).
 * Validates the format and rejects anything with suspicious characters.
 */
export function safeQIdSelector(qId: string): string {
  if (!/^[\w.-]+$/.test(qId)) {
    console.debug('[Qwik DevTools] Unexpected q:id format:', qId);
    return '[q\\\\:id="invalid"]';
  }
  return `[q\\\\:id="${qId}"]`;
}

/**
 * Type guard for unknown values that should be a plain object.
 * Avoids unsafe `as Record<string, unknown>` casts.
 */
export function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/**
 * Normalize a route path for comparison: always ends with '/'.
 */
export function normalizePath(path: string): string {
  return path.endsWith('/') ? path : `${path}/`;
}

/** Matches CSS hash class names generated by build tools (e.g. Cxmqbja) */
export const RE_CSS_HASH = /^[A-Z][a-z0-9]{2,9}$/;

/** Common component name prefixes that should NOT be treated as hashes */
export const RE_KNOWN_PREFIX =
  /^(Doc|Nav|App|List|Form|Menu|Card|Hero|Main|Page|View|Item|Tabs|Grid|Flex|Wrap|Icon|Logo|Text|Link|Body|Head)/;

/** Matches vowels (case-insensitive) */
export const RE_VOWELS = /[aeiou]/gi;

/** PascalCase class name - likely a component */
export const RE_PASCAL_CLASS = /^[A-Z][a-zA-Z0-9]+$/;

/** camelCase class name */
export const RE_CAMEL_CLASS = /^[a-z]+[A-Z][a-zA-Z0-9]*$/;

/** BEM-style block name (e.g. Header-modifier) */
export const RE_BEM_BLOCK = /^[A-Z][a-zA-Z]+-[A-Z]/;

/** Utility-first CSS class prefix (Tailwind, etc.) */
export const RE_UTILITY_PREFIX =
  /^(px|py|mx|my|mt|mb|ml|mr|pt|pb|pl|pr|flex|grid|block|inline|hidden|relative|absolute|fixed|sticky|text|bg|border|rounded|shadow|overflow|cursor|transition|transform|opacity|z|w|h|min|max|gap|space|font|leading|tracking|align|justify|items|self|place|col|row|sm|md|lg|xl|2xl|hover|focus|active|group|dark)[-:]/;

/** Short BEM-like class names with hyphen (e.g. my-component) */
export const RE_SHORT_HYPHEN = /^[a-z][\w]*-[\w-]+$/;

/** Short utility prefix (1-3 lowercase + colon/hyphen) */
export const RE_SHORT_UTILITY = /^[a-z]{1,3}[-:]/;

/** Dev-mode q:key (e.g. Header_component_0) */
export const RE_DEV_KEY = /^([A-Z][a-zA-Z0-9]+)_/;

/** Prod-mode hash q:key (e.g. w5MY:0G_0) */
export const RE_HASH_KEY_COLON = /^[a-zA-Z0-9]{2,6}:[a-zA-Z0-9]{2,6}/;

/** Prod-mode short hash key (e.g. ab_0) */
export const RE_HASH_KEY_SHORT = /^[a-zA-Z0-9]{2,4}_\d+$/;

/** Alphabetic-only string (for cleaned key names) */
export const RE_ALPHA_ONLY = /^[a-zA-Z]+$/;

/** Prod-mode QRL symbol prefix */
export const RE_PROD_SYMBOL = /^s_/;

export const MAX_TREE_DEPTH = 100;
export const MAX_ROUTE_DEPTH = 50;
export const DETAIL_WIDTH_MIN = 200;
export const DETAIL_WIDTH_MAX = 600;
export const DETAIL_WIDTH_DEFAULT = 340;
export const TREE_INDENT_PX = 14;
export const ROUTE_INDENT_PX = 18;
export const TOAST_DISMISS_MS = 4000;
export const MAX_LIVE_INPUTS = 5;
export const MAX_NEARBY_ELEMENTS = 8;
export const VIRTUAL_SCROLL_THRESHOLD = 500;
export const TREE_ROW_HEIGHT = 26;
export const VIRTUAL_SCROLL_OVERSCAN = 20;
